### What are NumPy and pandas?

- Numpy is an open source Python library used for scientific computing and provides a host of features that allow a Python programmer to work with high-performance arrays and matrices.

- pandas s a package for data manipulation that uses the DataFrame objects from R (as well as different R packages) in a Python environment.

- Both NumPy and pandas are often used together, as the pandas library relies heavily on the NumPy array for the implementation of pandas data objects and shares many of its features. In addition, pandas builds upon functionality provided by NumPy.

- Both libraries belong to what is known as the SciPy stack, a set of Python libraries used for scientific computing.

In [1]:
>>> data
>>>
array([[ 0.9526, -0.246 , -0.8856],
       [ 0.5639,  0.2379,  0.9104]])

NameError: name 'data' is not defined

In [ ]:
>>> data_frame 
>>>
  pop  state  year
0 1.5  Ohio   2000
1 1.7  Ohio   2001
2 3.6  Ohio   2002
3 2.4  Nevada 2001
4 2.9  Nevada 2002

NumPy, short for Numerical Python, is the fundamental package required for high performance scientific computing and data analysis. 
• ndarray, a fast and space-efficient multidimensional array providing vectorized arithmetic operations and sophisticated broadcasting capabilities
• Standard mathematical functions for fast operations on entire arrays of data without having to write loops
• Tools for reading / writing array data to disk and working with memory-mapped files
• Linear algebra, random number generation, and Fourier transform capabilities
• Tools for integrating code written in C, C++, and Fortran

#### The NumPy ndarray: A Multidimensional Array Object


- One of the key features of NumPy is its N-dimensional array object, or "ndarray", which is a fast, flexible container for large data sets in Python

In [ ]:
>>> data
>>>
array([[ 0.9526, -0.246 , -0.8856],
        [ 0.5639, 0.2379, 0.9104]])

In [ ]:
>>> data * 10
>>>
array([[ 9.5256, -2.4601, -8.8565],
        [ 5.6385, 2.3794, 9.104 ]])


In [ ]:
>>> data + data
>>>
array([[ 1.9051, -0.492 , -1.7713],
        [ 1.1277, 0.4759, 1.8208]])

In [ ]:
>>> data.shape 
>>> (2, 3)
>>> data.dtype
>>> dtype('float64')

#####  Creating ndarrays

In [ ]:
data1 = [6, 7.5, 8, 0, 1]

In [5]:
import numpy as np
arr1 = np.array(data1)

NameError: name 'data1' is not defined

In [ ]:
arr1

#### difference btw. array vs. list

- Arrays need to be declared. Lists don’t, since they are built into Python. In the examples above, you saw that lists are created by simply enclosing a sequence of elements into square brackets. Creating an array, on the other hand, requires a specific function from either the array module (i.e., array.array()) or NumPy package (i.e., numpy.array()). Because of this, lists are used more often than arrays.

- Arrays can store data very compactly and are more efficient for storing large amounts of data.

- Arrays are great for numerical operations; lists cannot directly handle math operations. For example, you can divide each element of an array by the same number with just one line of code. If you try the same with a list, you’ll get an error.

In [6]:
array = np.array([3, 6, 9, 12])
division = array/3
print(division)
print (type(division))

[1. 2. 3. 4.]
<class 'numpy.ndarray'>


In [7]:
list = [3, 6, 9, 12]
division = list/3

TypeError: unsupported operand type(s) for /: 'list' and 'int'

- Of course, it’s possible to do a mathematical operation with a list, but it’s much less efficient:

##### When to use list or array?
- If you need to store a relatively short sequence of items and you don’t plan to do any mathematical operations with it, a list is the preferred choice. 

- If you have a very long sequence of items, consider using an array. This structure offers more efficient data storage.

- If you plan to do any numerical operations with your combination of items, use an array. Data analytics and data science rely heavily on (mostly NumPy) arrays.

In [ ]:
##### difference between array vs. ndarray

- numpy.array is just a convenience function to create an ndarray; it is not a class itself.

- array is the function from numpy
- ndarray is the class generated from numpy.array

In [14]:
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]

In [15]:
arr2 = np.array(data2)

In [16]:
arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [17]:
arr2.ndim

2

In [18]:
arr2.shape

(2, 4)

In [19]:
arr2.dtype

dtype('int64')

- In addition to "np.array", there are a number of other functions for creating new arrays. 
- As examples, "zeros" and "ones" create arrays of 0’s or 1’s, respectively, with a given length or shape. 
- "empty" creates an array without initializing its values to any particular value.

In [20]:
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [21]:
np.zeros((3, 6))

array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [22]:
np.empty((2, 3, 2))

array([[[6.4e-323, 0.0e+000],
        [0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000]],

       [[0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000],
        [0.0e+000, 0.0e+000]]])

- It’s not safe to assume that np.empty will return an array of all zeros. 
- In many cases, as previously shown, it will return uninitialized garbage values.

In [23]:
# arange is an array-valued version of the built-in Python range function:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [28]:
# range in list
range(15)

TypeError: 'list' object is not callable

#### Data Types for ndarrays

In [35]:
arr1 = np.array([1.342, 2.234, 3.21], dtype=np.float64)
arr1

array([1.342, 2.234, 3.21 ])

In [36]:
arr2 = np.array([1.342, 2.234, 3.21], dtype=np.int32)
arr2

array([1, 2, 3], dtype=int32)

##### NumPy data types
Type
 int8, uint8
 int16, uint16
 int32, uint32
 int64, uint64
 float16
 float32
 float64, float128


In [37]:
arr = np.array([1, 2, 3, 4, 5])
arr.dtype

dtype('int64')

In [38]:
float_arr = arr.astype(np.float64)
float_arr.dtype

dtype('float64')

- In this example, integers were cast to floating point. 
- If I cast some floating point num- bers to be of integer dtype, the decimal part will be truncated:

In [39]:
arr = np.array([3.7, -1.2, -2.6, 0.5, 12.9, 10.1])
arr

array([ 3.7, -1.2, -2.6,  0.5, 12.9, 10.1])

In [40]:
arr.astype(np.int32)

array([ 3, -1, -2,  0, 12, 10], dtype=int32)

In [41]:
numeric_strings = np.array(['1.25', '-9.6', '42'], dtype=np.string_)
numeric_strings

array([b'1.25', b'-9.6', b'42'], dtype='|S4')

In [42]:
numeric_strings.astype(float)

array([ 1.25, -9.6 , 42.  ])

#### Operations between Arrays and Scalars

In [43]:
arr = np.array([[1., 2., 3.], [4., 5., 6.]])
arr

array([[1., 2., 3.],
       [4., 5., 6.]])

In [44]:
arr * arr

array([[ 1.,  4.,  9.],
       [16., 25., 36.]])

In [45]:
1 / arr

array([[1.        , 0.5       , 0.33333333],
       [0.25      , 0.2       , 0.16666667]])

In [46]:
arr**0.5

array([[1.        , 1.41421356, 1.73205081],
       [2.        , 2.23606798, 2.44948974]])

In [47]:
2 * arr

array([[ 2.,  4.,  6.],
       [ 8., 10., 12.]])

#### Basic Indexing and Slicing

In [57]:
arr = np.arange(10)
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [58]:
arr[5]

5

In [59]:
arr[5:8]

array([5, 6, 7])

In [ ]:
arr = np.arange(10)   # array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
arr[5]                # 5
arr[5:8]              # array([5, 6, 7])
arr[5:8] = 12         # array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])
arr_slice = arr[5:8]  # array([12, 12, 12])
arr_slice[1] = 12345  
arr                   # array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,9])
arr_slice[:] = 64
arr                   # array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

In [60]:
arr[5:8] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12,  8,  9])

In [63]:
arr_slice = arr[5:8]
arr_slice

array([12, 12, 12])

In [64]:
arr_slice[1] = 12345
arr

array([    0,     1,     2,     3,     4,    12, 12345,    12,     8,
           9])

In [65]:
arr_slice[:] = 64
arr

array([ 0,  1,  2,  3,  4, 64, 64, 64,  8,  9])

- As you can see, if you assign a scalar value to a slice, as in arr[5:8] = 12, the value is propagated (or broadcasted henceforth) to the entire selection. 
- An important first distinction from lists is that array slices are views on the original array. 
- This means that the data is not copied, and any modifications to the view will be reflected in the source array:

- If you want a copy of a slice of an ndarray instead of a view, you will need to explicitly copy the array; for example arr[5:8].copy().

In [65]:
arr = np.arange(10)
arr


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [66]:
arr_slice = arr[5:8].copy()
arr_slice

array([5, 6, 7])

In [67]:
arr_slice[1] = 120
arr_slice

array([  5, 120,   7])

In [68]:
arr

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

##### 2-Dimensional slicing

In [67]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
Dimensional slicing
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr2d
arr2d[2] array([7, 8, 9])
arr2d[:,2]  array([3, 6, 9])
arr2d[2,:]  array([7, 8, 9])
arr2d[0][2]  3
arr2d[0,2]  3
arr2d[0:2,1:3]  # array([[2, 3],[5, 6]])

In [68]:
arr2d[2]

array([7, 8, 9])

In [69]:
arr2d[:,2]

array([3, 6, 9])

In [70]:
arr2d[2,:]

array([7, 8, 9])

In [71]:
arr2d[0][2]

3

In [72]:
arr2d[0,2]

3

In [71]:
arr2d[0:2,1:3]

array([[2, 3],
       [5, 6]])

##### In multidimensional arrays, 2 X 2 X 3 array "arr3d"

In [73]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]], [[7, 8, 9], [10, 11, 12]]])

In [74]:
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [75]:
arr3d[0]

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
old_values = arr3d[0].copy()

In [77]:
arr3d[0] = 42
arr3d

array([[[42, 42, 42],
        [42, 42, 42]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [79]:
arr3d[0] = old_values
arr3d

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [80]:
arr3d[1, 0]  

array([7, 8, 9])

#### Indexing with slices

In [82]:
## one-dimensional 
arr = np.arange(10)
arr[1:6]

array([1, 2, 3, 4, 5])

In [90]:
## two-dimensional 
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [84]:
arr2d[2]

array([7, 8, 9])

In [85]:
arr2d[:2]

array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
arr2d[:2,1:]

array([[2, 3],
       [5, 6]])

In [87]:
arr2d[1, :2]

array([4, 5])

In [88]:
arr2d[2, :1]

array([7])

Let us make an example: 


![title](img/nparray.png)

##### indexing with an integer is different than indexing with a slice

In [86]:
# Make a 3d array:
import numpy as np
array = np.arange(60).reshape((3, 4, 5))
array

array([[[ 0,  1,  2,  3,  4],
        [ 5,  6,  7,  8,  9],
        [10, 11, 12, 13, 14],
        [15, 16, 17, 18, 19]],

       [[20, 21, 22, 23, 24],
        [25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34],
        [35, 36, 37, 38, 39]],

       [[40, 41, 42, 43, 44],
        [45, 46, 47, 48, 49],
        [50, 51, 52, 53, 54],
        [55, 56, 57, 58, 59]]])

In [87]:
# Indexing with ints gives a scalar
print (array[2, 3, 4] == 59)
# True


True


In [88]:
# Indexing with slices gives a 3d array
print (array[:2, :2, :2].shape)
# (2, 2, 2)


(2, 2, 2)


In [267]:
# Indexing with a mix of slices and ints will give an array with < 3 dims
print array[0, :2, :3].shape
# (2, 3)
print array[:, 2, 0:1].shape
# (3, 1)

(2, 3)
(3, 1)


##### add one-more dimension

- arr[..., None] takes an array of dimension N and "adds" a dimension "at the end" for a resulting array of dimension N+1.

In [94]:
x = np.array([[1,2,3],[4,5,6]])
print(x.shape)          # (2, 3)
x

(2, 3)


array([[1, 2, 3],
       [4, 5, 6]])

In [95]:
y = x[...,None]
print(y.shape)          # (2, 3, 1)
y


(2, 3, 1)


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

In [96]:
z = x[:,:,np.newaxis]
print(z.shape)          # (2, 3, 1)
z


(2, 3, 1)


array([[[1],
        [2],
        [3]],

       [[4],
        [5],
        [6]]])

#### adding Elements of the array

In [97]:
sum_val = np.sum(arr2d)
sum_val

45

In [98]:
arr2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [99]:
# sum along the rows
np.sum(arr2d,axis=1)

array([ 6, 15, 24])

In [100]:
# sum along the cols
np.sum(arr2d,axis=0)


array([12, 15, 18])

##### Saving and Loading Text Files

It will at times be useful to load data into vanilla NumPy arrays using np.loadtxt or the more specialized np.genfromtxt.

In [101]:
!cat data1.txt

cat: data1.txt: No such file or directory


In [102]:
import numpy as np
arr = np.loadtxt('data1.txt', delimiter=',')
arr

OSError: data1.txt not found.

##### Reshape array

In [104]:
arr = np.arange(8)

In [276]:
arr.reshape((4, 2))

ValueError: cannot reshape array of size 9 into shape (4,2)

In [106]:
arr.reshape((4, 2)).reshape((2, 4))

array([[0, 1, 2, 3],
       [4, 5, 6, 7]])

- One of the passed shape dimensions can be -1, in which case the value used for that dimension will be inferred from the data:

In [132]:
arr = np.arange(15).reshape((5, 3))

In [133]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [136]:
arr = np.arange(15).reshape((5, -1))
arr


array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

In [137]:
arr.flatten()

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [138]:
arr

array([[ 0,  1,  2],
       [ 3,  4,  5],
       [ 6,  7,  8],
       [ 9, 10, 11],
       [12, 13, 14]])

- The "flatten" method always returns a copy of the data:

- Functions like reshape and flatten, accept an order argument indicating the order to use the data in the array. This can be 'C' or 'F' in most cases 

- For historical reasons, row and column major order are also know as C and Fortran order, respectively. In FORTRAN 77, the language of our forebears, matrices were all column major.

In [140]:
arr = np.arange(12).reshape((3, 4), order = 'c')
arr

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [ ]:
arr = np.arange(12).reshape((3, 4), order = 'c')
arr  array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])
arr = np.arange(12).reshape((3, 4), order = 'F')
arr  array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

- C / row major order: traverse higher dimensions first (e.g. axis 1 before advancing on axis 0).

In [141]:
arr = np.arange(12).reshape((3, 4), order = 'F')
arr

array([[ 0,  3,  6,  9],
       [ 1,  4,  7, 10],
       [ 2,  5,  8, 11]])

- Fortran / column major order: traverse higher dimensions last (e.g. axis 0 before advancing on axis 1).

In [ ]:
##### Concatenating and Splitting Arrays 串联和分割

In [104]:
arr1 = np.array([[1, 2, 3], [4, 5, 6]])

In [105]:
arr2 = np.array([[7, 8, 9], [10, 11, 12]])

In [106]:
np.concatenate([arr1, arr2], axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [107]:
np.concatenate([arr1, arr2], axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

- There are some convenience functions, like vstack and hstack

In [108]:
np.vstack((arr1, arr2))

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [109]:
np.hstack((arr1, arr2))

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

- "split", on the other hand, slices apart an array into multiple arrays along an axis:

In [110]:
from numpy.random import randn
arr = randn(5, 2)
arr

array([[ 0.45705948, -0.26175087],
       [ 1.1196993 ,  0.04744375],
       [ 0.50102204,  0.3650982 ],
       [ 0.30441264, -0.3692802 ],
       [-0.97912275,  0.54674308]])

In [111]:
first, second, third = np.split(arr, [1, 3])

In [112]:
first

array([[ 0.45705948, -0.26175087]])

In [113]:
second

array([[1.1196993 , 0.04744375],
       [0.50102204, 0.3650982 ]])

In [114]:
third

array([[ 0.30441264, -0.3692802 ],
       [-0.97912275,  0.54674308]])

In [115]:
arr = randn(6, 2)
arr

array([[ 0.55390635, -0.47720088],
       [ 1.07902313,  0.10356945],
       [ 0.97381584,  0.80137613],
       [-0.37010738,  0.92406761],
       [ 0.42392763,  0.93102099],
       [-1.52621954, -0.79407226]])

In [116]:
first, second, third = np.split(arr, [1, 3])

In [117]:
first

array([[ 0.55390635, -0.47720088]])

In [118]:
second

array([[1.07902313, 0.10356945],
       [0.97381584, 0.80137613]])

In [119]:
third

array([[-0.37010738,  0.92406761],
       [ 0.42392763,  0.93102099],
       [-1.52621954, -0.79407226]])

##### Mathematical and Statistical Methods

- sum  $\;\;\;\;\;\;$     Sum of all the elements in the array or along an axis. 
- mean     $\;\;\;\;\;\;$          Arithmetic mean
- std, var   $\;\;\;\;\;\;$        Standard deviation and variance, respectively
- min, max      $\;\;\;\;\;\;$     Minimum and maximum.
- argmin, argmax  $\;\;\;\;\;\;$   Indices of minimum and maximum elements, respectively
- prod       $\;\;\;\;\;\;$     Product of elements starting from 0
- cumsum         $\;\;\;\;\;\;$    Cumulative sum of elements starting from 0
- cumprod       $\;\;\;\;\;\;$     Cumulative product of elements starting from 0



arr = np.random.randn(5, 4)       # normally-distributed data
arr

In [141]:
import numpy as np
arr = np.random.randn(5, 4)


In [135]:
arr.mean()

3.5

In [136]:
np.mean(arr)

3.5

In [137]:
arr.sum()

28

In [138]:
arr.std()

2.29128784747792

In [139]:
arr.mean(axis=1)

array([0.5, 2.5, 4.5, 6.5])

In [140]:
arr.sum(0)

array([12, 16])

In [142]:
arr = np.array([[1, 2, 3], [4,
5, 6], [7, 8, 9]])
arr

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [143]:
arr.prod()

362880

In [144]:
arr.prod(0)

array([ 28,  80, 162])

In [174]:
arr.cumsum(0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [171]:
arr.cumprod(1)

array([[  0,   0,   0],
       [  3,  12,  60],
       [  6,  42, 336]])

In [145]:
np.cumsum(arr)

array([ 1,  3,  6, 10, 15, 21, 28, 36, 45])

In [175]:
np.cumsum(arr, 0)

array([[ 0,  1,  2],
       [ 3,  5,  7],
       [ 9, 12, 15]])

In [178]:
np.cumprod(arr+1,0)

array([[  1,   2,   3],
       [  4,  10,  18],
       [ 28,  80, 162]])

In [182]:
b= np.arange(4)
b

array([0, 1, 2, 3])

In [183]:
b.cumsum()

array([0, 1, 3, 6])

In [184]:
b.cumprod()

array([0, 0, 0, 0])

#### Exercise 1. 

In [187]:
arr1 = np.arange(15)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [ ]:
# reshape arr1 to a 3X5 array  as 
# array([[ 0,  3,  6,  9, 12],
#        [ 1,  4,  7, 10, 13],
#        [ 2,  5,  8, 11, 14]])

In [225]:
## calculate the sum of each column of the above array
## array([ 3, 12, 21, 30, 39])

In [227]:
# put the column summation at the bottom of the array, like
# array([[ 0,  3,  6,  9, 12],
#       [ 1,  4,  7, 10, 13],
#       [ 2,  5,  8, 11, 14],
#       [ 3, 12, 21, 30, 39]])


In [230]:
# Slice the above array by removing the top row and the ending column,   like
# array([[ 1,  4,  7, 10],
#       [ 2,  5,  8, 11],
#       [ 3, 12, 21, 30]])

In [250]:
## calculate the product of all elements in each row of the above matrix, like 
## array([[  280],
##       [  880],
##       [22680]])

In [252]:
# put the above product elements at the right side of the array, like
# array([[    1,     4,     7,    10,   280],
#        [    2,     5,     8,    11,   880],
#        [    3,    12,    21,    30, 22680]])
#