In [ ]:

import numpy as np

#### arr: 		the input array
#### new_arr:	the new generated array as the output
#### calculate the product of each row and append to the array, use row_product to save the product value and add to the new array
def add_row_product_to_array(arr):
	row_product = arr.prod(1)				# write your code here
	new_arr =  np.hstack((arr,row_product.reshape(-1,1)))				# write your code here
	return new_arr


In [29]:
import numpy as np
arr = np.array([[0, 1],[2, 3],[4, 5],[6, 7]])
row_product = arr.prod(1)
np.hstack((arr,row_product.reshape(-1,1)))


array([[ 0,  1,  0],
       [ 2,  3,  6],
       [ 4,  5, 20],
       [ 6,  7, 42]])

In [ ]:
#### arr: 		the input array
#### new_arr:	the new generated array as the output
#### delete the top row and ending column from the array
def remove_topRow_endCol_from_array(arr):
	new_arr = arr[1:,:-1]				# write your code here
	return new_arr

In [7]:
import numpy as np
arr = np.array([[0, 1],[2, 3],[4, 5],[6, 7]])
new_arr = arr[1:,:-1]
new_arr

array([[2],
       [4],
       [6]])

In [ ]:
#### arr: 		the input array
#### new_arr:	the new generated array as the output
#### stack the column summation below the bottom of the array
def append_sum_of_array(arr):
	new_arr =  np.vstack((arr,arr.sum(0)))					# write your code here
	return new_arr 

In [11]:
import numpy as np
arr = np.array([[0, 1],[2, 3],[4, 5],[6, 7]])
new_arr = np.vstack((arr,arr.sum(0)))
new_arr

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [12, 16]])

In [ ]:
#### arr: 		the input array
#### nRow: 		the # of row in the reformed array
#### nCol: 		the # of column in the reformed array
#### new_arr:	the new reformed array as the output
#### reform the array to a new array with size(nRow,nCol)
def reform_array_dimension_col_wise(arr, nRow, nCol):
	new_arr =  arr.reshape(nRow,nCol)					# write your code here
	return new_arr

In [15]:
import numpy as np
nRow = 2
nCol= 6
arr = np.array([[0, 1,3],[2, 3,4],[4, 5,6],[6, 7,8]])
new_arr = arr.reshape(nRow,nCol)
new_arr

array([[0, 1, 3, 2, 3, 4],
       [4, 5, 6, 6, 7, 8]])